name: upload-download

on: [workflow_dispatch]

jobs:
  job1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello World" >> file.txt
    - uses: actions/upload-artifact@v2
      with:
        name: file
        path: file.txt

  job2:
    name: Download File
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: file
    - run: cat file.txt
